#!/usr/bin/env bash
# This script displays information about subdomains

# Function to display subdomain info
display_info() {
    local domain=$1
    local subdomain=$2
    local record_info=$(dig +short -t A ${subdomain}.${domain})

    echo "The subdomain ${subdomain} is a A record and points to ${record_info}"
}

# Check if domain argument is provided
if [ -z "$1" ]; then
    echo "Please provide a domain."
    exit 1
fi

# Check if subdomain argument is provided
if [ -n "$2" ]; then
    display_info $1 $2
else
    for subdomain in www lb-01 web-01 web-02; do
        display_info $1 $subdomain
    done
fi
