#!/usr/bin/env bash
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check if at least 4 parameters are provided
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

else
# Extract parameters
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file to the user's home directory on the server
scp -i "$HOME/.ssh/school" -o StrictHostKeyChecking=no "/alx-system_engineering-devops/0x0C-web_server/some_page.html" "ubuntu@18.214.87.164:~/"
fi

# Print success message
echo "File transferred successfully!"
