#!/usr/bin/env bash
# This script checks if Nginx is running and listening on port 80. If not, it starts Nginx and configures it to listen on port 80.
apt-get update -y
apt-get install -y nginx
service nginx start
