#!/bin/bash
-rwxr--r-- 1 root root 16 Jun  8 04:57 0-current_working_directory
-rwxr--r-- 1 root root 59 Jun  8 05:49 1-listit
-rwxr--r-- 1 root root 21 Jun  8 06:03 2-bring_me_home
-rwxr--r-- 1 root root 13 Jun  8 06:08 3-listfiles
-rwxr--r-- 1 root root 16 Jun  8 05:01 README.md
