#!/usr/bin/env bash
# This script creates a PID file, displays a message indefinitely, and handles signals

# Create a PID file
echo $$ > /var/run/myscript.pid

# Define what to do on SIGTERM
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM

# Define what to do on SIGINT
trap 'echo "Y U no love me?!"' SIGINT

# Define what to do on SIGQUIT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

# Display a message indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 1
done
