#!/usr/bin/env bash
# This script reads the /etc/passwd file and displays the username, user id, and home directory for each user

while IFS=: read -r username _ userid _ _ homedir _
do
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $homedir"
  echo ""
done < /etc/passwd
