#!/usr/bin/env bash
# This script reads the /etc/passwd file and displays information about each user

while IFS=: read -r username password userid groupid userinfo homedir commandshell
do
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $commandshell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
