#!/usr/bin/env bash
# This script installs the ufw firewall and setup a few rules on web-01

# First, install ufw
sudo apt-get update
sudo apt-get install ufw

# Allow SSH (port 22), HTTP (port 80), and HTTPS (port 443)
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable the firewall
sudo ufw enable
