#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
service nginx stop
sed -i 's/user root;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
service nginx start
