#!/bin/bash
#This script attempts to connect to the server at IP address 34.227.93.25
#using the username ubuntu and the private key located at ~/.ssh/school.
ssh -i ~/.ssh/school ubuntu@34.227.93.25
