#!/usr/bin/env bash
# This script creates an RSA key pair with a specific name, bit length,
# and passphrase
ssh-keygen -t rsa -b 4096 -f school -N "betty"

#ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'

# Explanation:
# -m PEM specifies the key format (PEM)
# -t rsa specifies the key type (RSA)
# -b 4096 specifies the number of bits
# -f school specifies the filename for the private key
# -N "betty" sets the passphrase
